version: 2

models:
  - name: final_url_performance
    description: The Click Performance report includes stats aggregated at each click level.
    columns:
      - name: _fivetran_id
        description: "{{ doc('_fivetran_id') }}"
      - name: _fivetran_synced
        description: "{{ doc('_fivetran_synced') }}"
      - name: account_descriptive_name
        description: "{{ doc('account_descriptive_name') }}"
      - name: ad_group_id
        description: "{{ doc('ad_group_id') }}"
      - name: ad_group_name
        description: "{{ doc('ad_group_name') }}"
      - name: ad_group_status
        description: "{{ doc('ad_group_status') }}"
      - name: campaign_id
        description: "{{ doc('campaign_id') }}"
      - name: campaign_name
        description: "{{ doc('campaign_name') }}"
      - name: campaign_status
        description: "{{ doc('campaign_status') }}"
      - name: clicks
        description: "{{ doc('clicks') }}"
      - name: cost
        description: "{{ doc('cost') }}"
      - name: customer_id
        description: "{{ doc('customer_id') }}"
      - name: date
        description: "{{ doc('date') }}"
      - name: effective_final_url
        description: "{{ doc('effective_final_url') }}"
      - name: external_customer_id
        description: "{{ doc('external_customer_id') }}"
      - name: impressions
        description: "{{ doc('impressions') }}"
    